name = "temp_warning"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["mehdi"]
maintainers = ["mehdi <mbdj@free.fr>"]
maintainers-logins = ["github-mbdj"]

executables = ["temp_warning"]
[[depends-on]]
pico_bsp = "^2.0.0"
